#log
logging:
  config: classpath:log4j2.xml
spring:
  datasource: 
    url: jdbc:mysql://10.1.5.77/springboot?useUnicode=true&characterEncoding=UTF-8
    username: zabbix
    password: shiny
    driver-class-name: com.mysql.jdbc.Driver