#log
logging:
  config: classpath:log4j2.xml
server:
  port: 8091
rocketmq:
  consumer:
    namesrvAddr: 10.1.5.77:9876
    groupName: vehicleProducerGroup
    topic: sms
    tag: verifycode
    consumeThreadMin: 20
    consumeThreadMax: 64