server:
  port: 8085
#log
logging:
  config: classpath:log4j2.xml
spring:
  jpa:
    show-sql: true
    hibernate:
      generate-ddl: true
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:backend
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
