#log
logging:
  config: classpath:log4j2.xml
server:
  port: 8090
rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: vehicleProducerGroup
    #mq的nameserver地址
    namesrvAddr: 10.1.5.77:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: vehicleProducer
    #topic名称
    topic: sms
    #根据实际情况设置消息的tag
    tag: verifycode
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
  consumer:
    namesrvAddr: 10.1.5.77:9876
    groupName: vehicleProducerGroup
    topic: sms
    tag: verifycode
    consumeThreadMin: 20
    consumeThreadMax: 64